# Configurazione database H2 in memoria
spring.datasource.url=jdbc:h2:mem:hackhubdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username= username
spring.datasource.password= password

# Configurazione JPA per creare le tabelle in automatico
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Abilita la console web di H2
spring.h2.console.enabled=true

# --- CONFIGURAZIONE PER ESEGUIRE IL DATA.SQL ---
# Forza Spring a lanciare il file SQL all'avvio
spring.sql.init.mode=always
# Dice a Spring: "Prima crea le tabelle vuote dalle classi Java, POI lancia il file SQL"
spring.jpa.defer-datasource-initialization=true